### ISSUE TITLE
Add mosaic logic for specifying panel order

### ISSUE THREAD

**Issue by bguthro** [smart-underworld/seestar_alp#147]
reference discussion:
https://discord.com/channels/1204838310841815040/1263544341406683186/1274545485297750159

An optional parameter for panel order might help multi-night runs where we would like to prioritize a panel for the darkest time of night.

`examples like: panel_set:1,2;4,6;5,6`

**Comment by smart-underworld** [comment]
Feature added:

The start_mosaic command will now take an optional parameter: "selected_panels". Example:

"selected_panels":"12;22"

Note that the session_time_sec will still have the original meaning as if all the panels are to be acquired. The reason is i expect this patient is called if some of the panels failed to be captured, so only the missing ones will be recaptured, with all the other parameters stay the same.
