### ISSUE TITLE
Using seestar_alp via web interface the first observation never stops

### ISSUE THREAD

**Issue by TimothyADavis** [smart-underworld/seestar_alp#192]
I have installed seestar_alp and it seems to work wonderfully, but when I initiate an observation it seems to get stuck doing the first job, and integrates forever on e.g. the first mosaic panel, rather than moving to the next one. The same thing seems to happen with schedules- once the first one is running it runs forever. 

I am running seestar_alp on MacOS, connecting to the seestar in station mode incase that is important information. Any tips on what I might be doing wrong? I see no error messages in the console.

**Comment by rrowley42** [comment]
Hi Timothy,

 

We usually work on this type of problem on the discord channel #seestar_alp-user-channel.  There is a log file written in the root directory of the project, alpaca.log. Look in there and see if you see anything odd, if not, please repost the question and the log in the user channel.  Just trying to steer you where you can get help.

 

Github https://github.com/smart-underworld

 

From: TimothyADavis ***@***.***> 
Sent: Saturday, August 31, 2024 8:04 AM
To: smart-underworld/seestar_alp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [smart-underworld/seestar_alp] Using seestar_alp via web interface the first observation never stops (Issue #192)

 

I have installed seestar_alp and it seems to work wonderfully, but when I initiate an observation it seems to get stuck doing the first job, and integrates forever on e.g. the first mosaic panel, rather than moving to the next one. The same thing seems to happen with schedules- once the first one is running it runs forever.

I am running seestar_alp on MacOS, connecting to the seestar in station mode incase that is important information. Any tips on what I might be doing wrong? I see no error messages in the console.

**Comment by rrowley42** [comment]
Moved conversation to Discord
