### ISSUE TITLE
Add frontend configuration to config.toml

### ISSUE THREAD

**Issue by erewhon** [smart-underworld/seestar_alp#26]
The port for the frontend should be configurable in config.toml.   

The frontend is presently hardcoded to port 5432.   For multi-telescope support, the frontend reads device/config.toml already, so that would be a logical place to add the frontend configuration.

See also: #33

**Comment by wileecyte** [comment]
This can fold in with fixing the Docker issue as well I'll take this.

**Comment by wileecyte** [comment]
Updated config.py to add uiport setting
Updated front/app.py to use config.py
Updated front/app.py to use network.ip_address network.port and network.uiport instead of hard-coded values
Updated docker/config.toml.example to include uiport setting

Tested with single and multiple device setups.  Works in Windows and on my Unraid server as a docker container.

**Comment by erewhon** [comment]
Resolved by #42
