### ISSUE TITLE
redo of dark frames

### ISSUE THREAD

**Issue by donpgolden** [smart-underworld/seestar_alp#528]
the startup skiped the polar align and did the dark frames.   So I manually did a polar align and when that operation finished it did dark frams again
[gensupportbundle.zip](https://github.com/user-attachments/files/18220398/gensupportbundle.zip)

**Comment by YungKC** [comment]
Reading an earlier log, you were trying to go to M35, which was failing because it cannot plate solve (cloudy??). While it is still trying to go there (failing still because of bad plate solving), you initiated a start up sequence. This really messed things up, since start up sequence assume Seestar is idle. 

I am not sure what you were trying to do. We suggest the very first thing you do is to do the start-up sequence first, before any other operations (especially gotos)

**Comment by YungKC** [comment]
I will mark this as closed for now. If you feel this sequence of event is not correct, you can reopen it.
